location = /billing/handle-donate.php {

    limit_except POST {
        deny all;
    }

    if ($http_user_agent ~* (curl|wget|python|nikto|sqlmap)) {
        return 403;
    }

    limit_req zone=one burst=5 nodelay;

    client_max_body_size 1m;

    include fastcgi_params;
    fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}